channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  # - python=3.7.5

  # - pip=20.1
  - Python=3.9.13                     # https://pyreadiness.org/3.9/ 
  - pip=22.3.1  
  - graphviz=2.48.0
  - openpyxl=3.0.9
  # - planar=0.4   
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - rpaframework==15.0.0 # https://rpaframework.org/releasenotes.html
      - rpaframework==22.0.0 # https://rpaframework.org/releasenotes.html
      - opencv-python==4.7.0.72
      - numpy==1.23.5
      - keras-ocr==0.8.5
      - scikit-image==0.20.0
      - pdf2image==1.16.3
      - torch==2.0.1  
      #- planar==0.4                 
      - tensorflow==2.11.0
      - transformers==4.28.1
      - Pillow==9.5.0       
      - timm==0.6.13
      - pymysql==1.0.3  
      - pandas==2.0.1
      - SQLAlchemy==2.0.15
      - azure-cognitiveservices-vision-computervision==0.9.0
      - msrest==0.7.1
      - pyodbc==4.0.39
     

    

